[workspace]
members = [
    "lib",
    "macro"
]
resolver = "2"

[workspace.package]
description = "retained"
version = "0.1.0"
edition = "2021"
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT or Apache-2.0"